name: 歌曲添加
description: 添加鸽宝会唱但歌单中没有的歌曲
title: '【歌曲添加】'
labels: [ "new song" ]

body:
  - type: markdown
    attributes:
      value: |
        ## 请补全标题并认真填写下方内容

  - type: checkboxes
    id: terms
    attributes:
      label: 请阅读以下注意事项，并勾选下方的确认框。
      options:
        - label: "我已经拉取仓库并查找过，歌曲不存在于歌单中。"
          required: true
        - label: "我已经在 [Pull Requests](https://github.com/boxie123/aige_song_list_xlsx/pulls?q=) 中找过我要添加的歌曲，没有找到相同问题的Pull Request。"
          required: true

  - type: textarea
    id: extra_info
    attributes:
      label: 额外信息（可选）
      description: 如：歌曲的链接？鸽宝何时演唱过？歌曲有哪些标签？
