name: 错误回报
description: 在浏览 鸽宝歌单 的过程中遇到了错误
title: '【错误回报】'
labels: [ "bug?" ]

body:
  - type: markdown
    attributes:
      value: |
        ## 感谢您愿意填写错误回报！
        ## 以下是一些注意事项，请务必阅读让错误能够更容易被处理

  - type: checkboxes
    id: terms
    attributes:
      label: 请阅读以下注意事项，并勾选下方的确认框。
      options:
        - label: "我已经多次 <kbd>Ctrl</kbd>+<kbd>F5</kbd> 刷新过，问题依旧存在。"
          required: true
        - label: "我已经在 [Issue Tracker](https://github.com/boxie123/aige_song_list/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。"
          required: true
        - label: 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）
          required: true

  - type: input
    id: browser_version
    attributes:
      label: 浏览器版本
      description: 如 Chrome 105.0.5195.102、Microsoft Edge 104.0.1293.70 等
    validations:
      required: true

  - type: input
    id: time
    attributes:
      label: 访问时间
      description: 如 2022-09-03 20:06:04
    validations:
      required: true

  - type: textarea
    id: bug_info
    attributes:
      label: 错误描述
      description: 描述你遇到的问题，需要怎么复现？期望的结果是什么？
    validations:
      required: true

  - type: textarea
    id: log
    attributes:
      label: 报错日志（如果有）以及补充说明
      description: <kbd>F12</kbd> 打开控制台查看报错信息
