name: "Update Song List"

on:
  push:
    branches:
      - main
    paths:
      - '鸽宝歌单整理.xlsx'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          repository: boxie123/aige_song_list
          ref: dev

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: temp_xlsx

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'

      - name: Install Dependencies
        run: poetry install --no-dev

      - name: Run main.py
        run: poetry run python temp_xlsx/main.py

      - name: Git Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add 鸽宝歌单整理.xlsx
          git commit -m "Update xlsx Song List"

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          branch: dev
          repository: boxie123/aige_song_list
